## Normalization Problem

In [7]:
import numpy as np

In [33]:
X = np.random.rand(5, 5) #Creates a random 5 by 5 array

In [11]:
X_normalized = (X - X.mean()) / X.std() #Normalizes the values in the array using the mean and standard deviation

In [56]:
np.save('X_normalized.npy', X_normalized) #Saves as npy file

In [58]:
print("Normalized Array:\n", X_normalized)

Normalized Array:
 [[ 0.52777604  0.16008399 -0.82195393  1.09880444 -0.49416078]
 [-0.90998888  0.28151159  0.76528427  1.41420341 -0.35672274]
 [-0.39654915  0.95922511 -1.25874997  0.52913751  0.41971547]
 [ 2.08496282 -0.48058225  0.98875543 -0.41498799 -1.35211186]
 [-0.76184377  1.73170513 -1.40287359 -0.985619   -1.32502128]]


## Divisible by 3 Problem

In [61]:
numbers = np.arange(1, 101) #Generates the first 100 positive integers

In [63]:
squares_array = numbers.reshape(10, 10)**2 #Reshapes this array into a 10 x 10 ndarray and computes the squares of these integers

In [65]:
div_by_3 = squares_array[squares_array % 3 == 0] #Uses boolean indexing to select elements from squares_array that are divisible by 3.

In [67]:
np.save('div_by_3', div_by_3) #Saves as npy file

In [69]:
print("Squares of the first 100 positive integers that are divisible by 3:\n", divisible_by_3) #Prints the squares of the first 100 positive integers that are divisible by 3

Squares of the first 100 positive integers that are divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
